/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/message": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.message.id"];
          body?: parameters["rowFilter.message.body"];
          subject?: parameters["rowFilter.message.subject"];
          topic?: parameters["rowFilter.message.topic"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["message"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** message */
          message?: definitions["message"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.message.id"];
          body?: parameters["rowFilter.message.body"];
          subject?: parameters["rowFilter.message.subject"];
          topic?: parameters["rowFilter.message.topic"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.message.id"];
          body?: parameters["rowFilter.message.body"];
          subject?: parameters["rowFilter.message.subject"];
          topic?: parameters["rowFilter.message.topic"];
        };
        body: {
          /** message */
          message?: definitions["message"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  message: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    body?: string;
    subject?: string;
    topic?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** message */
  "body.message": definitions["message"];
  "rowFilter.message.id": string;
  "rowFilter.message.body": string;
  "rowFilter.message.subject": string;
  "rowFilter.message.topic": string;
}

export interface operations {}

export interface external {}
